ALTER TABLE classes ADD COLUMN host_artist_id INTEGER REFERENCES artists(id) ON DELETE SET NULL;
ALTER TABLE classes ADD COLUMN total_slots INTEGER NOT NULL DEFAULT 0;
ALTER TABLE classes ADD COLUMN duration_min INTEGER NOT NULL DEFAULT 60;
